services:
  cahbox:
    build:
      context: ./
      dockerfile: .docker/Dockerfile
    container_name: cahbox
    environment:
      # DATA_PATH: /app_data
      NODE_EXTRA_CA_CERTS: /app_certs/localhost.crt
      TZ: America/Los_Angeles
    healthcheck:
      interval: "3s"
      retries: 3
      start_interval: "2s"
      # start_period: "5s"
      test: wget --no-verbose --tries=1 --spider --no-check-certificate https://localhost:3000 || exit 1
      timeout: "2s"
    image: theonewhoknocks/cahbox
    ports:
      # Map Local port to the Container's exposed port
      - "3000:3000"
    user: "${CURR_UID}:${CURR_GID}"
    volumes:
      - type: bind
        source: "${PWD}/certs"
        target: "/app_certs"
      # - "${PWD}/.app_data:/app_data"
  
  cahbox-dev:
    extends: cahbox # allows for just changing key pieces of data for development
    command: tail -F /dev/null # starts the container, and keeps it running
    container_name: cahbox-dev
    environment:
      NODE_ENV: development
    ports:
      # browserSync
      - "3001:3001"
      - "3002:3002"
      - "3003:3003"
      # inspector
      - "9229:9229"
    volumes:
      # Map shell files over, so they're maintained between sessions
      - "${PWD}/.docker/.vimrc:/home/node/.vimrc"
      - "${PWD}/.docker/.zshrc:/home/node/.zshrc"
      - "${PWD}/.ignore:/home/node/dev" # allows for .zsh_history to be written
      # Map the current directory over for development
      - "${PWD}:/home/node/app"
  
  cahbox-e2e:
    build:
      context: ./e2e/
      dockerfile: Dockerfile
    container_name: cahbox-e2e
    depends_on:
      - cahbox
    environment:
      BASE_URL: "https://cahbox:3000" # <PROTOCOL>://<CONTAINER_NAME>:<CONTAINER_PORT>
    hostname: e2etests
    ipc: host # Using `--ipc=host` is recommended when using Chrome (Docker docs). Chrome can run out of memory without this flag.
    ports:
      - "3001:3000"
    security_opt:
      - "seccomp:${PWD}/e2e/seccomp_profile.json"
    # working_dir: /e2e
    volumes:
      # - type: bind
      #   source: "/tmp/.X11-unix"
      #   target: "/tmp/.X11-unix"
      # - type: bind
      #   source: "${PWD}/e2e/results"
      #   target: "/e2e/results"
      - "${PWD}/e2e:/e2e"
      # - "${PWD}/e2e/tests:/e2e/tests"
      # - "${PWD}/e2e/playwright.config.js:/e2e/playwright.config.js"
      - "${PWD}/src/constants.js:/node_modules/@src/constants.js:r"
