services:
  cahbox:
    build:
      context: ./
      dockerfile: .docker/Dockerfile
    container_name: cahbox
    environment:
      NODE_EXTRA_CA_CERTS: /app_certs/localhost.crt
      TZ: America/Los_Angeles
    image: theonewhoknocks/cahbox
    ports:
      # Map Local port to the Container's exposed port
      - "3000:3000"
    user: "${CURR_UID}:${CURR_GID}"
    volumes:
      - type: bind
        source: "${PWD}/certs"
        target: "/app_certs"
  
  cahbox-dev:
    extends: cahbox # allows for just changing key pieces of data for development
    command: tail -F /dev/null # starts the container, and keeps it running
    container_name: cahbox-dev
    environment:
      NODE_ENV: development
    ports:
      # browserSync
      - "3001:3001"
      - "3002:3002"
      - "3003:3003"
      # inspector
      - "9229:9229"
    volumes:
      # Map shell files over, so they're maintained between sessions
      - "${PWD}/.docker/.vimrc:/home/node/.vimrc"
      - "${PWD}/.docker/.zshrc:/home/node/.zshrc"
      - "${PWD}/.ignore:/home/node/dev" # allows for .zsh_history to be written
      # Map the current directory over for development
      - "${PWD}:/home/node/app"
