module.exports = {
  WS_MSG__ANSWER_REVIEW_STATE_UPDATED: 'answer review state updated',
  WS_MSG__CARD_SELECTION_TOGGLED: 'card selection toggled',
  WS_MSG__CARDS_DEALT: 'cards dealt',
  WS_MSG__CARDS_SUBMITTED: 'cards submitted',
  WS_MSG__CHECK_USERNAME: 'check username',
  WS_MSG__CREATE_GAME: 'create game',
  WS_MSG__DEAL_CARDS: 'deal cards',
  WS_MSG__ENTER_ROOM: 'enter room',
  WS_MSG__JOIN_GAME: 'join game',
  WS_MSG__SET_ADMIN: 'set admin',
  WS_MSG__SET_ANSWER_REVIEW_STATE: 'set answer review state',
  WS_MSG__SET_CZAR: 'set czar',
  WS_MSG__SUBMIT_CARDS: 'submit cards',
  WS_MSG__TOGGLE_CARD_SELECTION: 'toggle card selection',
  WS_MSG__USER_JOINED: 'user joined',
  WS_MSG__USER_UPDATE: 'user update',
};